### ISSUE TITLE
All requests return Bad Request

### ISSUE THREAD

**Issue by Derppening** [kylambg/COMP4111Phase2#7]
### Issue description

Submitting any request to the server results in the server responding with `400 Bad Request`.

### Steps to reproduce this issue

1. Set up the database as stated in the README.
2. Run the project, either via IntelliJ IDEA or the provided JAR.
3. Make any request.

### What's the expected result?

A valid request should return `200 OK`.

### What's the actual result?

All requests returns `400 Bad Request`.

```
curl -v -X POST --data "{\"Username\": \"user00001\", \"Password\": \"pass00001\"}" http://localhost:8080/BookManagementService/login
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> POST /BookManagementService/login HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.70.0
> Accept: */*
> Content-Length: 50
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 50 out of 50 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Date: Sun, 31 May 2020 17:25:44 GMT
< Server: Test/1.1
< Content-Length: 0
< Connection: Close
< 
* Closing connection 0
```

### Additional Information

Since I still have the implementation to test, I decided to do some debugging and dig into the cause. It turns out that the cause is JDBC not knowing the database name:

```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'Comp4111'
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at DataBaseManager.Connector.getConnection(Connector.java:34)
	at DataBaseManager.LoginManager.login(LoginManager.java:45)
	at EventHandler.LoginHandler.lambda$handle$0(LoginHandler.java:60)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

As for why the database is not accessible, I noticed that the cause is due to bad capitalization. In particular, the database created by `Create.sql` is `comp4111` whereas the database connection points to `jdbc:mysql://localhost:3306/Comp4111`. According to [this](https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html) and [this](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_lower_case_table_names), on Linux the SQL server is defaulted to making database and table names **case-sensitive**. This explains why trying to access the database `comp4111` via the connection URL does not work as intended on Linux.

**Comment by kylambg** [comment]
I develope the project in Window environment, I haven't realized the environment of Linux is case sensitive, different from Window. Sorry about that, I will fix it
